version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_USER=guacamole
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"